blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/shagunmistry/moodtracker/discussions
    about: Ask questions or discuss ideas with the community
